mysql:
  host: "localhost"
  port: "3306"
  database: "database"
  username: "username"
  password: "password"

settings:
  clanDisband:
    deleteIfClanDisbanded: true
    consoleMessage: true
  #minutes
  updateAllKillsInterval: 60
  updateAllKillsMessage: true